which_game_cartridge:|md
# How do you know which cartridge?
    ...
    Raiders of the Lost Ark    CX2659       C   8      F8   X       J  RAIDERS
    Star Raiders               CX2660       U   8      F8   X      JK  STARRAID
    Basic Math                 CX2661       C   2           X       J  BASMATH
    Hangman                    CX2662       U   4           X       J  HANGMAN
    Road Runner                CX2663      ER  16      F6   X       J  ROADRUNR
    Brain Games                CX2664       U   2           X          BRAINGMS
    Frog Pond                  CX2665      PR   8      F8   X       J  FROGPOND
    Realsports Volleyball      CX2666       U   4           X          RS_VOLLY
    Realsports Soccer          CX2667       U   8      F8   X          RSSOCCER
    Realsports Football        CX2668       C   8      F8   X          RS_FOOTB
    Vanguard                   CX2669       C   8      F8   X          VANGUARD
    Atari Video Cube           CX2670       R   4           X       J  VIDCUBE
    Swordquest Waterworld      CX2671      UR   8      F8   X       J  SQ_WATER
    Swordquest Airworld        CX2672      NR  ??  ---No Known Copies Exist---
    Phoenix                    CX2673       C   8      F8   X       J  PHOENIX
    E.T. The Extra-Terrestrial CX2674       C   8      F8   X       J  E_T
    Ms. Pac-Man                CX2675       C   8      F8   X       J  MSPACMAN
    ...
|
