Atari 2600: {
  Memory {
  }
  Audio {
    link: layers.Audio
    TIA
  }
  Graphics {
    link: layers.Graphics
  }
  CPU {
    link: layers.CPU
    Clock
    Registers
    Instructions {
        link: layers.Instructions
    }
  }
  Inputs {
  }
  Inputs.link: layers.Inputs
}
Play: |md
  [Play](https://ajgrah2000.github.io/rusted_atari2600/)
  [Demo](./3lb_doctor_emu.atari)
  [Info](./3lb_doctor.nfo)
|

Cartridge: {
  ROM
  RAM
}
Cartridge.link: layers.Cartridge

Atari 2600 -> Cartridge

Atari 2600.link: layers.Atari 2600

layers: {
Cartridge: @../d2_images/atari2600_roms.d2
Inputs: @../d2_images/atari2600_inputs.d2
CPU: @../d2_images/atari2600_cpu.d2
Instructions: @../d2_images/atari2600_instructions.d2
Audio: @../d2_images/atari2600_audio.d2
Graphics: @../d2_images/atari2600_graphics.d2
Atari 2600: @../d2_images/atari2600_rust.d2
}
