overview:|md
  # Console emulation (in rust)
|
why?
languages?
targets?

overview.link: layers.emulation_motivation
why?.link: layers.emulation_motivation
languages?.link: layers.emulation_languages
targets?.link: layers.emulation_target_platforms

Atari2600.link: layers.Atari2600

Atari2600 Rust.link: layers.Atari2600 Rust

Sega Master System.link: layers.Sega Master System

layers: {
Atari2600: @../d2_images/atari2600.d2
Atari2600 Rust: @../d2_images/atari2600_rust.d2
Sega Master System: @../d2_images/sms.d2
emulation_motivation: @../d2_images/emulation_motivation.d2
emulation_languages: @../d2_images/emulation_languages.d2
emulation_target_platforms: @../d2_images/emulation_target_platforms.d2
}
